---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvnginix
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfsfileshare"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claimnginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
